# https://jupyterbook.org/en/stable/customize/config.html
name: qtclass-course-of-big-data-practice
title: 量潮课堂大数据应用项目实践
author: 量潮科技
description: 量潮课堂浙理工计院《大数据应用项目实践》校企合作课程
# Jupyter Book Config
only_build_toc_files: true
